### ISSUE TITLE
HW: not a valid protocol used in the URL for the FOM

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_TestSuiteDevelopment#50]
The HW app constructs the FOM URL from the resource in the JAR file.

````
final URL fddFileUrl = this.getClass().getClassLoader().getResource("HelloWorld.xml");
````

This results in a URL that is fine for Java RTIs (Pitch, Portico), but not for C++ RTIs (MaK)::

````
hla.rti1516e.exceptions.CouldNotOpenFDD: Illegal protocol jar, only the 'file' protocol is supported by the MAK RTI
````

As a result the HW application cannot be used with the MaK RTI.

**Comment by rhzg** [comment]
One way to solve this issue is to remove the __HelloWorld.xml__ file from the __HelloWorld-2.1.1.jar__ and place it inside the __lib__ folder.

Not sure how to solve this in a way that is compliant to the java build rules from gradle.

**Comment by rhzg** [comment]
I've included the HelloWorld.xml FOM file directly into the distribution, so that I could open the file with the File protocol (instead of the jar). That worked in my test environment.
